### ISSUE TITLE
Is there any option to disable default placeholder? 

### ISSUE THREAD

**Issue by brucelin0325** [olayinkaokewale/react-native-select-picker#3]
My app was messed up after updating the version to 62.2. And I found this package which is really great and helped me to save time on this. 

Thank you for all the work you have done for this. 

I'm just wondering if there's an option to disable default placeholder? I set default value instead of this placeholder so don't' want to list default placeholder as an option. 

e.g: 
------select-----
option1
option2
option3

TO

option1
option2
option3

Please advise.

**Comment by olayinkaokewale** [comment]
@brucelin0325 thanks for the suggestion. There will be an update to that effect very soon. Cheers!

**Comment by brucelin0325** [comment]
@olayinkaokewale 
Awesome, that would be helpful for the others with a similar situation. I can't wait for the next release. 
Thank you again.

**Comment by olayinkaokewale** [comment]
Issue fixed [here](https://github.com/olayinkaokewale/react-native-select-picker/commit/cefe4725ec915995e6e1fffe0f2571861a9d8c76) please update your version to 0.0.81 using:

`npm i -S react-native-form-select-picker@0.0.81`

Thanks @brucelin0325 for calling my attention to it.
